name: Update Modrinth Mods

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-mods:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch Modrinth Mods
        run: |
          curl -s https://api.modrinth.com/v2/user/SmileLulz/project \
          | jq '[.[] | {name: .title, description: .description, url: .project_url, icon: .icon_url, last_updated: .updated}]' > mods.json

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add mods.json
          git commit -m "Update Modrinth mods"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
